title: "Datensummit '17"
description: "Das Fest am 28. & 29. April in Berlin"
url: https://datensummit.de
markdown: kramdown
exclude:
  - "vendor"
  - "CNAME"
  - "Gemfile*"
  - "mission"
  - "README.md"
  - "*.sh"
  - "doc/"
  - "local/"
  - "update_avatars.py"
  #- "projekte" # uncomment line to speed up jekyll build for development
  #- "blog" # uncomment line to speed up jekyll build for development
  #- "termine" # uncomment line to speed up jekyll build for development
  #- "presse" # uncomment line to speed up jekyll build for development
sass:
    style: :compressed
permalink: /blog/:title
excerpt_separator: "\n"
paginate: 5
paginate_path: "blog/:num"
gems:
  - jekyll-sitemap
  - jekyll-paginate
collections:
  labs:
  termine:
  stories:
    output: true
    permalink: /stadtgeschichten/:path/
  stories_en:
    output: true
    permalink: /en/stadtgeschichten/:path/
